# Numpy

Exercícios de Numpy

In [ ]:
import numpy as np


## Gerando números inteiros aleatórios no

O random.randint é uma função da biblioteca padrão do Python (random) usada para gerar números inteiros aleatórios dentro de um intervalo definido.

In [ ]:
#1- Crie um array unidimensional de 50 elementos contendo numeros inteiros aleatorios entre 10 e 100.

array = np.random.randint(
    10,      # low → valor mínimo
    101,     # high → valor máximo. Como o limite superior não entra, usamos 101 para ir até 100.
    size=50  # size → quantidade de elementos.
)

print(array)

[ 53  90  35  12  28  30  45  34  78  43  19  83  72  28  57  25  54  57
  75  58  75  21  61  21  89  77  69  99 100  38  32  11  19  82  32  29
  93  80  77  53  24  74  64  94  15  12  94  16  93  77]


## Explicação

1.  np.arange(1, 17) → cria uma sequência de números inteiros começando em 1 até 16 (o 17 não entra porque o limite superior é exclusivo).

2.  .reshape(4, 4) → reorganiza essa sequência em formato de matriz 4x4 (4 linhas e 4 colunas).

3. matriz[-1] → acessa a última linha da matriz.

* Em Python, o índice -1 sempre significa o último elemento (no caso de uma matriz, a última linha).

In [ ]:
#2-  Gere uma matriz 4x4 com numeros inteiros de 1 a 16 e extraia a ultima linha.

matriz = np.arange(1, 17).reshape(4, 4)# .reshape(4, 4) → transforma em uma matriz 4x4.
print("Matriz 4x4:\n",matriz)

ultima_linha = matriz[-1, :] # matriz[-1] → seleciona a última linha (o -1 significa “último índice”).
print("\nÚltima linha:", ultima_linha)


Matriz 4x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Última linha: [13 14 15 16]


##Explicação:

1. np.zeros(15) → cria um array de 15 posições, todas preenchidas com 0.

2. array[4:10] = 1 → substitui os valores do índice 4 até 9 (que correspondem à 5ª até a 10ª posição) por 1.

In [ ]:
#3- Crie um array de zeros com comprimento 15 e substitua os valores da 5ª a 10ª posicao por 1.

array = np.zeros(15)
print("Array inicial:", array)

# Substituir os valores da 5ª até a 10ª posição por 1
array[4:10] = 1
print("Array modificado:",array)



Array inicial: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array modificado: [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


##Explicação:

1. np.median(array) → calcula a mediana do array, ou seja, o valor que está no meio quando os elementos estão ordenados.

* Se o array tiver número par de elementos, ele faz a média dos dois valores centrais.

2. np.bincount(array) → conta quantas vezes cada número inteiro aparece no array.

3. .argmax() → retorna o índice do valor que aparece mais vezes.

In [ ]:
#4- Gere um array de 100 numeros inteiros aleatorios e encontre a mediana e a moda dos valores.

array = np.random.randint(1, 101, size=100)
print("Array gerado: \n", array)

# Calcular a mediana
mediana = np.median(array)
print("Valor da Mediana:", mediana)

# Calcular a moda
moda = np.bincount(array).argmax()
print("Valor da Moda:", moda)





Array gerado: 
 [ 62  40  63  77   4  36  16  44 100  26  49  45  21  61  92  49  93  57
  48  94  71  36  89  91  34  33  48  37  67   8  93  86  78  88  96  38
  91   8  24 100  88  34  45  61  63  44  21  22  67   5  54  25  25  39
  55  42  17  25  21  96  24  81  34  93  56  74  60  48  13  93  10  64
  83  34  44  25  52   7  75  64  93  18  83   8  62  12  20   1  43  75
  13  83  19  48  28  99  83  49   4  60]
Valor da Mediana: 48.0
Valor da Moda: 93


## Explicação
1. np.random.randint(1, 101, size=20) → cria um array com 20 números inteiros aleatórios entre 1 e 100.
2. array % 3 == 0 → cria uma máscara booleana, que é True para os números múltiplos de 3.

3. array[mascara] = -3 → substitui todos os valores onde a máscara é True pelo valor -3.

In [ ]:
 #5- Crie um array de 20 elementos contendo n´umeros entre 1 e 100 e substitua todos os valores multiplos de 3 por -3.

array = np.random.randint(1, 101, size=20)
print("Array gerado: \n", array)
# Substituir todos os valores múltiplos de 3 por -3
array[array % 3 == 0] = -3
print("Array modificado: \n", array)


Array gerado: 
 [27 20 93 35 77 94 42 45 50 97 99 31 86 17 76 37 26 97 82 56]
Array modificado: 
 [-3 20 -3 35 77 94 -3 -3 50 97 -3 31 86 17 76 37 26 97 82 56]


##Explicação somar coluna

1. np.random.rand(5,5) → cria números decimais aleatórios entre 0 e 1.

2. np.sum(array, axis=0) → soma verticalmente cada coluna da matriz.
*  axis=0 indica que a operação é feita ao longo das linhas.

In [ ]:
#6- Gere uma matriz 5x5 de n´umeros aleat´orios entre 0 e 1 e encontre a soma de cada coluna

array = np.random.rand(5,5)
print("Matriz gerada: \n", array)

# Calcular a soma de cada coluna
soma_colunas = np.sum(array, axis=0)
print("Soma de cada coluna:", soma_colunas)


Matriz gerada: 
 [[0.54859981 0.54165616 0.68581852 0.15154079 0.5364885 ]
 [0.16556503 0.84836492 0.7041616  0.41844791 0.47485957]
 [0.60265602 0.15147166 0.69662979 0.56664875 0.44934476]
 [0.02397815 0.26579166 0.81028315 0.4258586  0.99842632]
 [0.15304741 0.58778339 0.72012603 0.87288549 0.55932116]]
Soma de cada coluna: [1.49384642 2.39506779 3.61701909 2.43538155 3.01844031]


## Explicação:

1. np.random.randint(1, 101, size=10) → cria 10 números inteiros aleatórios entre 1 e 100.

2. np.corrcoef(array1, array2) → retorna a matriz de correlação 2x2:

* correlacao[0,1] ou correlacao[1,0] é o valor que representa a correlação entre os dois arrays.

* correlacao[0,0] e correlacao[1,1] são sempre 1 (correlação do array com ele mesmo).

In [2]:
#7- Crie dois arrays de numeros aleatorios e encontre a correlacao entre eles.

array1 = np.random.randint(1, 101, size=10)
print(array1)

array2 = np.random.randint(1, 101, size=10)
print(array2)

correlacao = np.corrcoef(array1, array2)
print("\nMatriz de Correlação:\n", correlacao)



[97  8 68 14  4 99 99 84 62 97]
[92 59  9 57 64 35 43 47 69 41]

Matriz de Correlação:
 [[ 1.         -0.20330062]
 [-0.20330062  1.        ]]


## Explicação

1. np.random.randint(1, 101, size=(3,3)) → cria uma matriz 3x3 com números inteiros aleatórios entre 1 e 100 (101 é exclusivo).
2. np.square(array) → eleva cada elemento da matriz ao quadrado.

In [3]:
#8- Gere uma matriz 3x3 com n´umeros inteiros aleat´orios e eleve todos os seus elementos ao quadrado

array = np.random.randint(1, 101, size=(3,3))
print("Matriz gerada: \n", array)

# Elevar todos os elementos ao quadrado
quadrado = np.square(array)
print("\nMatriz elevada ao quadrado: \n", quadrado)



Matriz gerada: 
 [[17 68 28]
 [24 71 65]
 [42 80 45]]

Matriz elevada ao quadrado: 
 [[ 289 4624  784]
 [ 576 5041 4225]
 [1764 6400 2025]]


## Explicação
1. array.min() → menor valor do array

2. array.max() → maior valor do array

3. array - array.min() → desloca todos os valores para começar do zero

4. / (array.max() - array.min()) → divide pelo intervalo, garantindo que o maior valor fique 1

In [5]:
#9-  Crie um array com 10 numeros aleatorios e normalize seus valores entre 0 e 1.

array = np.random.randint(1, 101, size=10)
print("Array gerado: \n", array)

# Normalizar os valores entre 0 e 1
array = (array - array.min()) / (array.max() - array.min())
print("\nArray normalizado: \n", array)


Array gerado: 
 [68 22 48 38 71 67 81 46 48 31]

Array normalizado: 
 [0.77966102 0.         0.44067797 0.27118644 0.83050847 0.76271186
 1.         0.40677966 0.44067797 0.15254237]


## Explicação
1. np.eye(6, dtype=int) → cria uma matriz identidade 6x6 (1s na diagonal e 0s no restante).

2. np.arange(6) → gera os índices [0, 1, 2, 3, 4, 5].

3. array[np.arange(6), np.arange(6)] → seleciona exatamente a diagonal principal.

4. np.arange(1, 7) → gera os valores [1, 2, 3, 4, 5, 6].

Esses valores substituem os da diagonal.

In [9]:
#10- Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescentes de 1 a 6.

array = np.random.randint(1, 101, size=(6,6))
print("Matriz identidade:\n", array)

# Substituir a diagonal principal por valores de 1 a 6
array[np.arange(6), np.arange(6)] = np.arange(1, 7)
print("\nMatriz com diagonal substituída:\n", array)

Matriz identidade:
 [[41 12 81 72 49 48]
 [ 8 34 81 54 31 45]
 [ 3 21 19 68 17 56]
 [83 18 16 26 84 59]
 [26  5 29  2 66 53]
 [15 17 89 85 58 96]]

Matriz com diagonal substituída:
 [[ 1 12 81 72 49 48]
 [ 8  2 81 54 31 45]
 [ 3 21  3 68 17 56]
 [83 18 16  4 84 59]
 [26  5 29  2  5 53]
 [15 17 89 85 58  6]]


##Explicação

1. np.random.randint(1, 101, size=100) → gera 100 inteiros entre 1 e 100.

2. np.bincount(array) → cria um array onde o índice representa o número e o valor representa quantas vezes ele apareceu.

* Exemplo: se array = [2, 2, 5], então np.bincount(array) = [0, 0, 2, 0, 0, 1].

3. np.argmax(contagem) → retorna o índice do valor máximo, ou seja, o número mais frequente.

4. contagem[valor_mais_frequente] → mostra quantas vezes ele apareceu.

In [12]:
#11- Gere um array de 100 numeros inteiros e encontre o valor que mais se repete no array.

array = np.random.randint(1, 101, size=100)
print("Array gerado: \n", array)


# Contar as ocorrências de cada número
contagem = np.bincount(array)

# Encontrar o valor que mais se repete
valor_mais_repetido = np.argmax(contagem)

frequencia = contagem[valor_mais_repetido]

print("\nValor que mais se repete:", valor_mais_repetido)
print("Frequência:", frequencia)

Array gerado: 
 [ 79  87  18  91  66  25  93  44  43  14  22  52  32  77   8  71  47   4
  74  61  23  44  94  28  82  91  36  59  94  56  41  25  18  49  33  61
  94   4  28  44  89  32  76  93  42  31  68  22  46  58  26  76  73  11
  49  85  54  48  85  89  42   8  17 100  48  31  92  50  75  30  62  10
  61  24  48  96  81  62  23  52  50  47  76  49  83  32  93  82  90  14
  51  78   3  13  46  43  13  40  95  17]

Valor que mais se repete: 32
Frequência: 3


## Explicação
1. np.arange(4) → gera os índices [0, 1, 2, 3].

2. array[np.arange(4), np.arange(4)] → seleciona exatamente os elementos da diagonal principal (posição [0,0], [1,1], [2,2], [3,3]).

3. = 7 → substitui esses valores por 7.

In [13]:
#12 Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.

array = np.random.randint(1, 101, size=(4,4))
print("Matriz gerada: \n", array)

# Substituir a diagonal principal por 7
array [np.arange(4), np.arange(4)] = 7
print("\nMatriz modificada: \n", array)


Matriz gerada: 
 [[54 49 82 63]
 [12  7  7 27]
 [22  2 56 91]
 [14 99 84 18]]

Matriz modificada: 
 [[ 7 49 82 63]
 [12  7  7 27]
 [22  2  7 91]
 [14 99 84  7]]


## Explicação

1. np.arange(0, 20, 2) → gera números de 0 até 20 (exclusivo), de 2 em 2.
2. np.cumsum(array) → soma os elementos de forma cumulativa.
* O resultado é um novo array mostrando o acúmulo progressivo da soma.

In [14]:
#13 - Crie um array contendo os 10 primeiros numeros pares e calcule sua soma cumulativa.

array = np.arange(0, 20, 2)
print("Array gerado: \n", array)

# Calcular a soma cumulativa
sum_cum = np.cumsum(array)
print("\nSoma cumulativa: \n", sum_cum)

Array gerado: 
 [ 0  2  4  6  8 10 12 14 16 18]

Soma cumulativa: 
 [ 0  2  6 12 20 30 42 56 72 90]


## Explicação

1. array1 - array2 → o NumPy faz a subtração elemento a elemento.

2. np.mean(diferenca) → calcula a média de todos os valores do array resultante.

In [17]:
#14 - Calcule a diferenca entre dois arrays de numeros aleatorios de mesmo comprimento e encontre a media das diferencas.


array1 = np.random.randint(30,100, size=(4,4))
print("Array 1: \n", array1)

array2 = np.random.randint(1,20, size=(4,4))
print("Array 2: \n", array2)

diferenca = array1 - array2
print("\nDiferença entre os arrays: \n", diferenca)

media_diferenca = np.mean(diferenca)
print("\nMédia das diferenças: \n", media_diferenca)



Array 1: 
 [[89 42 96 82]
 [71 93 53 77]
 [51 53 97 42]
 [85 94 45 87]]
Array 2: 
 [[ 1 16  7  8]
 [13  6  5  3]
 [ 6  2 10  6]
 [11 18  2  1]]

Diferença entre os arrays: 
 [[88 26 89 74]
 [58 87 48 74]
 [45 51 87 36]
 [74 76 43 86]]

Média das diferenças: 
 65.125


# Explicação

1.  Parte usa indexação booleana do NumPy.
* Onde a condição (array > 50) é verdadeira, ele troca o valor por 50.

In [19]:
#15-  Gere um array contendo 20 numeros e substitua todos os valores maiores que 50 por 50.


array = np.random.randint(1, 101, size=20)
print("Array gerado: \n", array)

# Substituir os valores maiores que 50 por 50
array[array > 50] = 50
print("Array:", array)

Array gerado: 
 [22 89 38 88 44 77 36 47 46 80 79 34 14 84 40  1 71 95 17 45]
Array: [22 50 38 50 44 50 36 47 46 50 50 34 14 50 40  1 50 50 17 45]


## Explicação:
1. reshape(3,4) transforma o array de 1 dimensão (12 elementos) em uma matriz de 3 linhas e 4 colunas.

* Ele apenas muda a forma do array, não cria novos números.



In [20]:
# 16 -  Crie um array unidimensional e reorganize seus valores em uma matriz 3x4.

array = np.random.randint(1, 101, size=12)
print("Array gerado: \n", array)

matriz = array.reshape(3, 4)
print("\nMatriz modificada: \n", matriz)


Array gerado: 
 [18 16 95 94 88 10 27 80  8 42 57 52]

Matriz modificada: 
 [[18 16 95 94]
 [88 10 27 80]
 [ 8 42 57 52]]


In [21]:
#17- Gere uma matriz 4x4 de numeros inteiros aleatorios e multiplique cada valor por sua posicao na matriz

array = np.random.randint(1, 101, size=(4,4))
print("Matriz gerada: \n", array)

multiclicar = array * np.arange(1, 17).reshape(4, 4)
print("\nMatriz modificada: \n", multiclicar)
#

Matriz gerada: 
 [[36  2 53 16]
 [26 32 53 78]
 [31 62 84 87]
 [41  1 52 67]]

Matriz modificada: 
 [[  36    4  159   64]
 [ 130  192  371  624]
 [ 279  620  924 1044]
 [ 533   14  780 1072]]


## Explicação:

1. array % 5 == 0
→ Verifica quais elementos do array são múltiplos de 5.
Isso gera um array booleano (True onde é múltiplo de 5).

2. array[array % 5 == 0] = 0
→ Substitui todos os elementos que são múltiplos de 5 por 0.


In [23]:
#18- Crie um array de 10 elementos contendo numeros entre 1 e 100 e substitua todos os valores multiplos de 5 por 0.

array = np.random.randint(1, 101, size=10)
print("Array gerado: \n", array)

array[array % 5 == 0] = 0
print("Array modificado: \n", array)


Array gerado: 
 [53  2 46  5 46 80 20  9 63 76]
Array modificado: 
 [53  2 46  0 46  0  0  9 63 76]


## Explicação:


**Produto escalar:**

1. np.dot(array1, array2)→ Soma do produto de cada elemento correspondente.

**Norma do vetor:**

2. np.linalg.norm(array1)→ Calcula a magnitude do vetor (√(x₁² + x₂² + ...)).

**Produto escalar normalizado:**

3. cos_theta = produto_escalar / (norma1 * norma2)→ Fórmula de cosseno do ângulo entre dois vetores:cos𝜃= (A*B)/(A*B)


**Ângulo em radianos e graus:**

4. angulo_rad = np.arccos(cos_theta) | angulo_graus = np.degrees(angulo_rad)

*  np.arccos retorna em radianos, np.degrees converte para graus.

In [25]:
# 19- Crie dois arrays de numeros inteiros aleatorios de tamanho 20 e calcule o angulo entre eles (produto escalar normalizado)

array1 = np.random.randint(1, 101, size=20)
print("Array 1: \n", array1)

array2 = np.random.randint(1, 101, size=20)
print("Array 2: \n", array2)

# Calcular o produto escalar normalizado
produto_escalar = np.dot(array1, array2)
print("\nProduto Escalar: \n", produto_escalar)

#normas dos vetores
norma_array1 = np.linalg.norm(array1)
norma_array2 = np.linalg.norm(array2)

print("\nNorma do array 1: \n", norma_array1)
print("\nNorma do array 2: \n", norma_array2)

# Produto escalar normalizado (cosθ)
cos_theta = produto_escalar / (norma_array1 * norma_array2)
print("\nProduto Escalar Normalizado: \n", cos_theta)

#Calcular o angulo em radianos
angulo_radianos = np.arccos(cos_theta)
print("\nAngulo em radianos: \n", angulo_radianos)

#Converter para graus
angulo_graus = np.degrees(angulo_radianos)
print("\nAngulo em graus: \n", angulo_graus)

Array 1: 
 [ 71  21  60  91  93  13  27  41  60  10 100  15  90  92  81  44  54  75
  41  43]
Array 2: 
 [ 76  82  34  62 100   5  34  72   1  65  86  63  99   2  58  65  92  77
  43  41]

Produto Escalar: 
 69211

Norma do array 1: 
 282.21977251780214

Norma do array 2: 
 291.15803269015265

Produto Escalar Normalizado: 
 0.8422846973677091

Angulo em radianos: 
 0.5692885238689247

Angulo em graus: 
 32.61782974292201


## Explicação

1. axis=1 indica que a operação é feita ao longo das colunas, ou seja, para cada linha, retorna o menor valor presente nela.



In [26]:
#20- Crie uma matriz de numeros inteiros e encontre o valor mınimo de cada linha.

matriz = np.random.randint(1, 101, size=(4,4))
print("Matriz gerada: \n", matriz)

minimo_linha = np.min(matriz, axis=1)
print("\nValor mínimo de cada linha: \n", minimo_linha)


Matriz gerada: 
 [[44 96 70 44]
 [19 47 90 93]
 [48 42 61 87]
 [82 35 95 36]]

Valor mínimo de cada linha: 
 [44 19 42 35]
